### ISSUE TITLE
Banshee Regression?

### ISSUE THREAD

**Issue by zarubaf** [pulp-platform/snitch#127]
@SamuelRiedel @paulsc96 CI seems to have troubles compiling `banshee` since a couple of hours - maybe a regression with a new `rustc` release? Can somebody of you please look into this when he has some time at hand (🙈 )?

**Comment by paulsc96** [comment]
Yes, it is apparently illegal now to internally annotate match blocks in Rust :man_shrugging:. #128 fixes this by external annotation.
