### ISSUE TITLE
Compiler support for ISSR

### ISSUE THREAD

**Issue by diorga** [pulp-platform/snitch#133]
I have noticed that ISSR instructions have been added to the banshee simulator. However, the tests now need compiler support (the _scfgwi_ instruction is not supported). Is there a link to the new compiler?

**Comment by noah95** [comment]
We are working on compiler support for the SSR instruction and will release it in the next weeks. Until then, you can use [the runtime library](https://github.com/pulp-platform/snitch/blob/ca929ad402878b64ab3746d86fb25ae6d245930f/sw/snRuntime/src/ssr_v2.c#L20) to configure the SSRs

**Comment by diorga** [comment]
Is there a way to compile tests that use ISSR at the moment? 
For example, I would like to compile the following [test](https://github.com/pulp-platform/snitch/blob/master/sw/banshee/tests/spmm_issr_frep.c)

**Comment by noah95** [comment]
Unfortunately that is not possible yet, sorry.

**Comment by diorga** [comment]
Thank you for the information! 
I would be very interested to use it once it is available.

**Comment by noah95** [comment]
Ok, w've now release the [LLVM compiler for Snitch](https://github.com/pulp-platform/snitch-llvm). Closing this for now, let me know if you encounter any issues
