### ISSUE TITLE
Negative stride

### ISSUE THREAD

**Issue by diorga** [pulp-platform/snitch#146]
Can the stride for the SSR loops be negative? Currently, I see that this is not allowed by the function arguments. 

For example, the `snrt_ssr_loop_1d` has the third argument `size_t i0` which only allows for unsigned values, therefore only allowing a positive stride.

**Comment by noah95** [comment]
Stride can be negative. [The value written to the SSR configuration register](https://github.com/pulp-platform/snitch/blob/ca929ad402878b64ab3746d86fb25ae6d245930f/sw/snRuntime/src/ssr_v2.c#L20) with `scfgwi` is a relative stride. The value is added to the last pointer location of the previous dimension in HW, you need to take that into account when configuring the DM.

The `snrt_ssr_loop` functions take an absolute stride as argument as this is more intuitive and calculate the relative stride. We never used negative absolute stride, but this is possible.
