### ISSUE TITLE
Banshee: Atomic support on main memory

### ISSUE THREAD

**Issue by zarubaf** [pulp-platform/snitch#197]
As @fischeti pointed out, opposed to the RTL, Banshee currently does not support atomics on its main memory. Would be very neat to align those - also in light of the overall synchronization discussion.

**Comment by SamuelRiedel** [comment]
Hm, that should actually be [supported](https://github.com/pulp-platform/snitch/blob/078a14ab715a759a6146609cea3fba53a3dcf4c2/sw/banshee/src/engine.rs#L622) and is tested [here](https://github.com/pulp-platform/snitch/blob/078a14ab715a759a6146609cea3fba53a3dcf4c2/sw/banshee/tests/atomics.c#L94). What exactly is failing? Or am I just misunderstanding what you mean by main memory?

**Comment by zarubaf** [comment]
I think that is solved and was a misunderstanding :-)
