### ISSUE TITLE
banshee/RTL wakeup register discrepancy

### ISSUE THREAD

**Issue by noah95** [pulp-platform/snitch#246]
In RTL, the wakeup register is per-cluster and cannot wake harts from other clusters (introduced in  #111). Furthermore, the hartid always begins at `0`.

Banshee implements a global wakeup register where all cores in the system can be woken up. It further considers the base-hartid when waking up cores as added in #58.

This hinders a "unified" runtime.

I propose to change the banshee behaviour to mimic the RTL implementation. @SamuelRiedel @fischeti are there applications that depend on being able to wake cores from other clusters in banshee? Is the mempool implementation different than the current Snitch implementation?

For inter-cluster communication we can use the CLINT that is implemented in banshee & RTL.

**Comment by SamuelRiedel** [comment]
Sounds good to me. I am now aware of any application relying on this. It can be that the [wfi test](https://github.com/pulp-platform/snitch/blob/master/sw/banshee/tests/wfi.c) has to be adapted, though.

This behavior would also be fine for MemPool, since it is a single cluster system.

**Comment by noah95** [comment]
Okay thanks for oppinion! Will address this in #237

**Comment by fischeti** [comment]
That's fine by me. I don't use the wakeup feature in my applications (yet)

> In RTL, the wakeup register is per-cluster and cannot wake harts from other clusters (introduced in #111). Furthermore, the hartid always begins at 0.

Not sure if this is relevant, but in case of Occamy we have a manager core with hartid `0` and therefore a base-hartid of 1

**Comment by noah95** [comment]
> Not sure if this is relevant, but in case of Occamy we have a manager core with hartid `0` and therefore a base-hartid of 1

Agree, but still: The wakeup register is only for the (9) cores per cluster and bit `0` is for hart 0 of the cluster

https://github.com/pulp-platform/snitch/blob/0ff968e59bf3b569e0f8aa144d8954ddafe0d903/hw/ip/snitch_cluster/src/snitch_cluster_peripheral/snitch_cluster_peripheral_reg.hjson#L121-L135
