### ISSUE TITLE
axi: Outdated dw_converter

### ISSUE THREAD

**Issue by SamuelRiedel** [pulp-platform/snitch#283]
There is a bug in the current version of the data width converter that leads to requests being lost. This prevented me from accessing the soc control registers with Snitch. This bug is fixed in the [upstream AXI repo](https://github.com/pulp-platform/axi/commit/ada7c9e20c415c979d674f48d0e19ccdd0cf3f81#diff-5b1f86474f46437643d8849846d1f2c8e854c5058278f69c28cf5334a35f3427), but Snitch currently follows the DMA branch.

The solution would be to pull in the fixed dw_converter, but I am unsure how you want to handle this. Should we create a patch that only updates the dw_converter, or do you want to update the complete AXI repo?

**Comment by SamuelRiedel** [comment]
cc: @zarubaf @thommythomaso @paulsc96

**Comment by zarubaf** [comment]
My opinion is that updating the repo at this stage of the project isn't very wise. So I would recommend the patch option.  

I would probably cherry-pick the DW changes onto the `axi_dma_tbenz` branch of pulp-platform/axi and update the vendor here (`./util/vendor.py hw/vendor/pulp_platform.vendor.hjson --update --commit`).
