### ISSUE TITLE
ci: Forced python version

### ISSUE THREAD

**Issue by fischeti** [pulp-platform/snitch#301]
The new python version `3.10` used in the CI breaks the `yamlfmt` package (which requires `ruamel.yaml<0.16`).  the CI can be forced to python version `<=3.9` where the CI is working again for the moment (#300). But ultimately, the package conflict needs to resolved. `yamlfmt` seems to be not maintained anymore, therefore we need to figure out a new solution (e.g. `yamllint`)

**Comment by paulsc96** [comment]
AFAICT, this is no longer an issue after migration. If it is, please reopen.
