### ISSUE TITLE
Bender >=0.24 no longer resolves `export_include_dir` hierarchically

### ISSUE THREAD

**Issue by paulsc96** [pulp-platform/snitch#326]
See https://github.com/pulp-platform/bender/pull/70. This breaks many of our IP and vendor includes with own headers (e.g. `common_cells`).

The simplest fix would be to enforce the "new" conventions and consider the use of header includes a direct dependency, i.e. include a sub-IP as a direct dependency in any IP using its headers.

**Comment by accuminium** [comment]
To make this change less urgent, you can keep using Bender 0.23.2 for now with
```sh
curl --proto '=https' --tlsv1.2 https://pulp-platform.github.io/bender/init -sSf | sh -s -- 0.23.2
```

**Comment by accuminium** [comment]
To clarify the problem, Bender 0.24.0 no longer makes exported include directories (i.e., those specified under `export_include_dirs`) available globally. Instead, it makes them available only through dependencies. This is actually intended behavior:  `` `include``ing the headers of a package implies a dependency on that package. If that breaks any setup, it means dependencies are insufficiently or incorrectly specified.

If the implementation is wrong or you have questions, please let me know.
