### ISSUE TITLE
Quadrant Control: Wrong Reset value or comment

### ISSUE THREAD

**Issue by noah95** [pulp-platform/snitch#342]
Comment says `Held in reset (i.e. signal high) by default` but signal is `active low` and reset value is `1`. Either the comment is wrong or the reset value. What is the intended behavior?

https://github.com/pulp-platform/snitch/blob/ac033c2cd611573037392b459c189d7f80725dc0/hw/system/occamy/src/occamy_quadrant_s1_ctrl/occamy_quadrant_s1_reg.hjson.tpl#L27-L30

**Comment by paulsc96** [comment]
Indeed. I will have to think about which reset value is safer.

**Comment by paulsc96** [comment]
Fixed in #345.
