### ISSUE TITLE
Floor Plan Area

### ISSUE THREAD

**Issue by davemap** [pulp-platform/snitch#43]
Hi, Thanks for all your help on the other thread. I am considering using a 32-bit snitch with the FPU in a university project. The other option I was looking at was using a Cortex-M0 but it doesn't have a FPU. The M0 has a  0.11 mm2 floor plan area in a 180nm process. Do you have a rough idea what the floor plan area might be in this configuration for the snitch? 

Thank you very much!

**Comment by gurkaynak** [comment]
You can take a look at https://arxiv.org/pdf/2002.10143.pdf to get an idea on how large the design is in terms of kilo Gate Equivalents (kGE). In a 180nm a 2-input NAND gate (one GE) is maybe around 10 squm (give or take 20% or so). So just the core (without the FPU) would maybe be around the same area (which is not surprising), but the FPU would be much larger (about 5x or so). 

Anyway, in any implementation, it will be the memories that take the most area (roughly 1kbit == 1kGE) and if you follow that you can see that roughly 1 sqmm is 8-16kByte  in 180nm.  Of course these numbers are for back of the envelope calculations, for better estimations, you should do some synthesis trials yourself.

**Comment by davemap** [comment]
Thank you very much, I will try and do some synthesis and see where I get to.
