### ISSUE TITLE
how to solve this issue:multiple definition of `_start'; 

### ISSUE THREAD

**Issue by ansen09** [pulp-platform/snitch#446]
hi, when i use docker and follow the Quick Start to run the platform . when i go to the step of Build the software with make cmd , some errors like this blow:
/tools/riscv/bin/../lib/gcc/riscv64-unknown-elf/8.3.0/../../../../riscv64-unknown-elf/bin/ld: ../snRuntime/libsnRuntime-cluster.a(start_snitch.S.o): in function `snrt.crt0.init_global_pointer':
(.init+0x0): multiple definition of `_start'; /tools/riscv/bin/../lib/gcc/riscv64-unknown-elf/8.3.0/../../../../riscv64-unknown-elf/lib/crt0.o:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
benchmark/CMakeFiles/benchmark-matmul-ssr.dir/build.make:106: recipe for target 'benchmark/benchmark-matmul-ssr' failed
make[2]: *** [benchmark/benchmark-matmul-ssr] Error 1
CMakeFiles/Makefile2:251: recipe for target 'benchmark/CMakeFiles/benchmark-matmul-ssr.dir/all' failed
make[1]: *** [benchmark/CMakeFiles/benchmark-matmul-ssr.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2

I try to add -nostartfiles cmd to the gcc option , but this issue is unresolved.

my question is how to solve this issue "multiple definition of `_start'"

thanks !

**Comment by frieden-ls** [comment]
i get a same question,I use ubuntu18.04 and follow quick start to build software with 
cd sw/build
cmake ..
make.There are som errors as followed:
snRuntime/CMakeFiles/snRuntime-cluster.dir/build.make:81: recipe for target 'snRuntime/CMakeFiles/snRuntime-cluster.dir/src/platforms/shared/start.c.o' failed
make[2]: *** [snRuntime/CMakeFiles/snRuntime-cluster.dir/src/platforms/shared/start.c.o] Error 1
CMakeFiles/Makefile2:189: recipe for target 'snRuntime/CMakeFiles/snRuntime-cluster.dir/all' failed
make[1]: *** [snRuntime/CMakeFiles/snRuntime-cluster.dir/all] Error 2
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2
