### ISSUE TITLE
cmake does not work anymore for software setup

### ISSUE THREAD

**Issue by JosseVanDelm** [pulp-platform/snitch#489]
Hi,

I'm following the getting started guide, and it seems that #475 broke that part?

Thanks!

Best regards,

Josse

**Comment by mihaivitanescu** [comment]
Hi Josse,

I have the same issue. I tried different branches like fix/docker and got a step further.
However the generated make file still fails with some header files issues. Hope someone can have a look into this.

Thank you whomever may see this and can help!
:+1: 

BR,
Mihai

**Comment by JosseVanDelm** [comment]
Hi @mihaivitanescu, I was told to use b9fe555 instead of `master` since the people working on this are revamping the software stack and the accompanied  build system

**Comment by mihaivitanescu** [comment]
Hi Josse,
thank you for the help. It brought me a step further to run the cmake but some files seems to be not properly configured:
mduser@debianFPGA:~/master/checkout/snitch/hw/system/snitch_cluster/sw/build$ make
Scanning dependencies of target snRuntime-cluster
[  3%] Building C object snRuntime/CMakeFiles/snRuntime-cluster.dir/src/platforms/shared/start.c.o
In file included from /home/mduser/master/checkout/snitch/sw/snRuntime/src/platforms/shared/../../team.h:5,
                 from /home/mduser/master/checkout/snitch/sw/snRuntime/src/platforms/shared/start.c:4:
/home/mduser/master/checkout/snitch/sw/snRuntime/include/snrt.h: In function ‘snrt_interrupt_global_enable’:
/home/mduser/master/checkout/snitch/sw/snRuntime/include/snrt.h:208:5: warning: implicit declaration of function ‘set_csr’ [-Wimplicit-function-declaration]
  208 |     set_csr(mstatus, MSTATUS_MIE);  // set M global interrupt enable
      |     ^~~~~~~
/home/mduser/master/checkout/snitch/sw/snRuntime/include/snrt.h:208:13: error: ‘mstatus’ undeclared (first use in this function)
  208 |     set_csr(mstatus, MSTATUS_MIE);  // set M global interrupt enable
      |             ^~~~~~~
/home/mduser/master/checkout/snitch/sw/snRuntime/include/snrt.h:208:13: note: each undeclared identifier is reported only once for each function it appears in
/home/mduser/master/checkout/snitch/sw/snRuntime/include/snrt.h: In function ‘snrt_interrupt_global_disable’:
/home/mduser/master/checkout/snitch/sw/snRuntime/include/snrt.h:215:5: warning: implicit declaration of function ‘clear_csr’ [-Wimplicit-function-declaration]
  215 |     clear_csr(mstatus, MSTATUS_MIE);
      |     ^~~~~~~~~
/home/mduser/master/checkout/snitch/sw/snRuntime/include/snrt.h:215:15: error: ‘mstatus’ undeclared (first use in this function)
  215 |     clear_csr(mstatus, MSTATUS_MIE);
      |               ^~~~~~~
/home/mduser/master/checkout/snitch/sw/snRuntime/include/snrt.h: In function ‘snrt_interrupt_enable’:
/home/mduser/master/checkout/snitch/sw/snRuntime/include/snrt.h:226:13: error: ‘mie’ undeclared (first use in this function)
  226 |     set_csr(mie, 1 << irq);
      |             ^~~
/home/mduser/master/checkout/snitch/sw/snRuntime/include/snrt.h: In function ‘snrt_interrupt_disable’:
/home/mduser/master/checkout/snitch/sw/snRuntime/include/snrt.h:235:15: error: ‘mie’ undeclared (first use in this function)
  235 |     clear_csr(mie, 1 << irq);
      |               ^~~
/home/mduser/master/checkout/snitch/sw/snRuntime/include/snrt.h: In function ‘snrt_interrupt_cause’:
/home/mduser/master/checkout/snitch/sw/snRuntime/include/snrt.h:243:12: warning: implicit declaration of function ‘read_csr’ [-Wimplicit-function-declaration]
  243 |     return read_csr(mcause) & ~0x80000000;
      |            ^~~~~~~~
/home/mduser/master/checkout/snitch/sw/snRuntime/include/snrt.h:243:21: error: ‘mcause’ undeclared (first use in this function)
  243 |     return read_csr(mcause) & ~0x80000000;
      |                     ^~~~~~
/home/mduser/master/checkout/snitch/sw/snRuntime/src/platforms/shared/start.c: In function ‘_snrt_init_team’:
/home/mduser/master/checkout/snitch/sw/snRuntime/src/platforms/shared/start.c:64:29: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
   64 |     team->barrier_reg_ptr = (uint32_t)spm_start + bootdata->tcdm_size +
      |                             ^
/home/mduser/master/checkout/snitch/sw/snRuntime/src/platforms/shared/start.c:86:31: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   86 |     team->peripherals.clint = (uint32_t *)bootdata->clint_base;
      |                               ^
make[2]: *** [snRuntime/CMakeFiles/snRuntime-cluster.dir/build.make:82: snRuntime/CMakeFiles/snRuntime-cluster.dir/src/platforms/shared/start.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:169: snRuntime/CMakeFiles/snRuntime-cluster.dir/all] Error 2
make: *** [Makefile:114: all] Error 2
mduser@debianFPGA:~/master/checkout/snitch/hw/system/snitch_cluster/sw/build$

**Comment by GiannaP** [comment]
Dear all,
we are currently still heavily in a transition phase to separate the `snitch_cluster` setup from `occamy`. Furthermore, `banshee` will soon also live in its own repository.

The new `snitch_cluster` repo is already available here: [https://github.com/pulp-platform/snitch_cluster](https://github.com/pulp-platform/snitch_cluster)
The corresponding Documentation can be found here: [https://pulp-platform.github.io/snitch_cluster/](https://pulp-platform.github.io/snitch_cluster/)

The new `occamy` repo is currently under development. Until we release it, I recommend staying on the commit [b9fe555](https://github.com/pulp-platform/snitch/commit/b9fe5550e26ea878fb734cfc37d161f564252305).

Note that this repository will get archived once the two new repositories are somewhat stable.

**Comment by JosseVanDelm** [comment]
Thanks @GiannaP!
Just a quick notif for others that commit b9fe555 also exists in the new `snitch_cluster` repository, but that the commit hash changed to [`snitch-cluster hash d6a83aa`](https://github.com/pulp-platform/snitch_cluster/tree/d6a83aa0a8ec9667f225ee8e30ee1c50fe1d32fb)
