### ISSUE TITLE
Banshee support floating-point printf

### ISSUE THREAD

**Issue by diorga** [pulp-platform/snitch#86]
Whenever I try to print a floating-point value, banshee does not actually print the value. This feature would be very useful for debugging.

**Comment by zarubaf** [comment]
I agree, unfortunately, I think that is a shortcoming of the embedded [`printf`](https://github.com/pulp-platform/snitch/blob/master/sw/snRuntime/vendor/printf.c)  library we are using. The only advantage is that we do not need to support floating-point instructions and can execute the library on all of the cores in a system (also the data mover core without FPU).

**Comment by diorga** [comment]
Ok, understood. Thanks!
