### ISSUE TITLE
Banshee casting

### ISSUE THREAD

**Issue by diorga** [pulp-platform/snitch#87]
It would be very useful if casting instructions would be implemented in banshee. These are the **fcvt** instructions.

**Comment by noah95** [comment]
#63 implemented some more, specifically
```
fcvt.w.d
fcvt.w.s
fcvt.wu.s
fcvt.wu.d
fcvt.d.s
fcvt.s.d
```
Which ones are still missing? You can take this PR as a guideline on implementing more.

**Comment by diorga** [comment]
I used the new version of banshee and it works nicely. Thanks!
